spring:
  profiles:
    active: local
  application:
    name: azit

  threads:
    virtual:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  jackson:
    deserialization:
      read_unknown_enum_values_as_null: true

security:
  permit-all-paths:
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-ui.html"
    - "/api/v1/swagger-test/**"

kakao:
  oauth:
    auth-url: https://kauth.kakao.com
    api-url: https://kapi.kakao.com

apple:
  oauth:
    apple-url: https://appleid.apple.com

naver:
  search:
    api-url: https://openapi.naver.com

default:
  member:
    profile-images:
      - "/default/member/default_1.svg"
      - "/default/member/default_2.svg"
      - "/default/member/default_3.svg"
      - "/default/member/default_4.svg"
      - "/default/member/default_5.svg"
      - "/default/member/default_6.svg"
  crew:
    image: "/default/crew/crew_default.svg"

management:
  endpoints:
    web:
      exposure:
        include: health # 무중단 배포에 필요한 health 엔드포인트만 노출
  endpoint:
    health:
      show-details: never # 서버 내부 정보(DB 상태, 디스크 용량 등)를 숨기고 "UP/DOWN" 결과만 보여줌

springdoc:
  swagger-ui:
    tags-sorter: alpha # 컨트롤러 알파벳 순
    operations-sorter: method # HTTP 메서드 순
