spring:
  profiles:
    active: local
  application:
    name: azit

  threads:
    virtual:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100

security:
  permit-all-paths:
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-ui.html"
    - "/api/v1/swagger-test/**"

oauth:
  kakao:
    auth-url: https://kauth.kakao.com
    api-url: https://kapi.kakao.com
  apple-url: https://appleid.apple.com
