spring:
  profiles:
    active: local
  application:
    name: azit

  threads:
    virtual:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

security:
  permit-all-paths:
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-ui.html"
    - "/api/v1/swagger-test/**"

oauth:
  kakao:
    auth-url: https://kauth.kakao.com
    api-url: https://kapi.kakao.com
  apple-url: https://appleid.apple.com

default:
  member:
    profile-images:
      - "/default/members/default_1.svg"
      - "/default/members/default_2.svg"
      - "/default/members/default_3.svg"
      - "/default/members/default_4.svg"
      - "/default/members/default_5.svg"
      - "/default/members/default_6.svg"
  crew:
    image: "/default/crews/crew_default.svg"
