spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: dev-azit-storage
      cloudfront:
        domain: dev-images.azitcrew.com
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}

swagger:
  server:
    url: https://dev-api.azitcrew.com
    description: Develop Server

security:
  cors:
    allowed-origins:
      - "https://dev-api.azitcrew.com"
      - "https://dev.azitcrew.com"
      - "http://localhost:3000"
      - "https://appleid.apple.com"
    allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed-headers: ["*"]
    allow-credentials: true

oauth:
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET}
    admin-key: ${KAKAO_ADMIN_KEY}
    redirect-uri: https://dev.azitcrew.com/oauth/callback?provider=kakao
  apple:
    team-id: ${APPLE_TEAM_ID}
    client-id: ${APPLE_SERVICE_ID}
    key-id: ${APPLE_KEY_ID}
    key-path: ${APPLE_KEY_PATH}
    redirect-uri: https://dev-api.azitcrew.com/api/v1/auth/social-login/apple
    success-redirect-uri: https://dev.azitcrew.com/login-success

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-seconds: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration-seconds: ${JWT_REFRESH_EXPIRATION}
  refresh-token-name: azit_rt_dev
  cookie:
    secure: true

server:
  port: 8080