name: AZIT CI/CD
run-name: AZIT server deployed to (${{ github.event.inputs.profile }}) by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      profile:
        description: '적용할 프로파일 선택'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/azit-server:latest
            ${{ secrets.DOCKER_USERNAME }}/azit-server:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.profile || 'dev' }}
    steps:
      - name: Get GitHub Runner IP
        id: ip
        run: echo "ipv4=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_OUTPUT

      - name: Authorize Security Group Inbound Rule # 임시로 깃허브 액션 포트 열기
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_GIT_ACTIONS_SG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_GIT_ACTIONS_SG_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            # .env 파일 생성
            cat <<EOF > .env
            TARGET_PROFILE=${{ github.event.inputs.profile }}
            IMAGE_TAG=${{ github.sha }}
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}
            AWS_S3_SECRET_KEY=${{ secrets.AWS_S3_SECRET_KEY }}
            KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}
            KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
            KAKAO_ADMIN_KEY=${{ secrets.KAKAO_ADMIN_KEY }}
            KAKAO_REDIRECT_URL=${{ secrets.KAKAO_REDIRECT_URL }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            JWT_ACCESS_EXPIRATION=${{ secrets.JWT_ACCESS_EXPIRATION }}
            JWT_REFRESH_EXPIRATION=${{ secrets.JWT_REFRESH_EXPIRATION }}
            APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}
            APPLE_SERVICE_ID=${{ secrets.APPLE_SERVICE_ID }}
            APPLE_KEY_ID=${{ secrets.APPLE_KEY_ID }}
            APPLE_KEY_PATH=${{ secrets.APPLE_KEY_PATH }}
            APPLE_REDIRECT_URL=${{ secrets.APPLE_REDIRECT_URL }}
            EOF

            sudo docker compose pull app
            sudo docker compose up -d app
            sudo docker image prune -a -f

      - name: Revoke Security Group Inbound Rule
        if: always() # 배포 실패 시에도 보안을 위해 포트 닫기
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_GIT_ACTIONS_SG_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_GIT_ACTIONS_SG_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  notify:
    needs: [ build-and-push, deploy ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          noprefix: true
          status: ${{ needs.build-and-push.result == 'success' && needs.deploy.result == 'success' && 'success' || 'failure' }}
          title: "🚀 AZIT 서버 배포 결과"
          description: |
            **배포 환경:** `${{ github.event.inputs.profile }}`
            **결과:** ${{ (needs.build-and-push.result == 'success' && needs.deploy.result == 'success') && '✅ 성공' || '❌ 실패' }}
            **로그 확인:** [GitHub Actions 링크](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          color: ${{ (needs.build-and-push.result == 'success' && needs.deploy.result == 'success') && '0x00ff00' || '0xff0000' }}